name: Heroku Cotinuous Deployment

on:
  push:
    brances: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
      - uses: actions/checkout@master
        with:
          node-version: 14
      - run: heroku git:remote -a arisna-devops-demo
      - run: git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
